# Product Root Definition
id: "prod_devspec"
name: "DevSpec"
version: "0.1.0"
description: "A self-evolving, serial conversational intelligent pair-programming environment."
domains:
  - id: "dom_core"
    name: "Core Engine"
    description: "The brain of the system, handling the knowledge graph and context."
  - id: "dom_cli"
    name: "CLI Interface"
    description: "The user interaction layer using Typer."
  - id: "dom_quality"
    name: "Quality Assurance"
    description: "Tools for testing and auditing code compliance."
