# Product Root Definition (L-1 Level)
# 职责：定义产品愿景和领域概要，不包含 Feature 列表
# Feature 属于哪个 Domain 由 Feature YAML 中的 domain 字段声明

id: prod_devspec
name: "DevSpec"
version: "0.3.0"

# Product Vision - 用于需求分析 Step 2: 判断是否符合 Vision
description: "A self-evolving, serial conversational intelligent pair-programming environment."
vision: |
  DevSpec 是专为 "Super Individuals" (超级个体) 设计的串行会话式智能结对编程环境。
  它不仅是开发业务软件的工具，更是一个自我进化的生命体 (Self-Evolving Life Form)。
  核心理念：Spec First (文档是唯一事实来源), Serial Flow (专注单任务), Recursive Evolution (工具由工具自身构建)。

# Domain 概要 (L0 Level) - 用于需求分析 Step 3: 分析涉及的 Domain
# 注意：不包含 features 列表，Domain → Feature 关系通过 Feature.domain 字段建立
domains:
  - id: dom_core
    name: "Core Engine"
    description: "系统的'大脑'，负责维护知识图谱、解析代码、管理上下文。"
    exports:
      - name: "query_graph"
        signature: "query_graph(query: GraphQuery) -> List[Node]"
        description: "Query the SpecGraph knowledge graph"
      - name: "get_context"
        signature: "get_context(node_id: str, depth: int = 1) -> NodeGraph"
        description: "Get node context with related nodes"
      - name: "sync_graph"
        signature: "sync_graph() -> SyncResult"
        description: "Sync YAML files to database"

  - id: dom_cli
    name: "CLI Interface"
    description: "系统的'AI 接口'，为 AI Agent (Claude Code, Gemini CLI) 提供命令行工具，支持 AI 开发产品需求。"
    exports:
      - name: "run_command"
        signature: "run_command(cmd: str, args: List[str]) -> int"
        description: "Execute a CLI command"

  - id: dom_specview
    name: "SpecGraph Viewer"
    description: |
      系统的'人类窗口'，为人类用户提供 Web 界面展示 SpecGraph 知识库。
      设计原则：Read-Only (只读), Progressive Disclosure (渐进式披露),
      Spatial Consistency (空间一致性), Guided Exploration (引导式探索)。
    exports:
      - name: "serve"
        signature: "serve(port: int = 8000) -> None"
        description: "Start the local web server for SpecGraph viewing"
      - name: "get_navigation_guide"
        signature: "get_navigation_guide() -> List[NavItem]"
        description: "Get navigation guide items for home page (Hierarchy, Design, Relations, Search)"
      - name: "get_node_relations"
        signature: "get_node_relations(node_id: str, depth: int = 2) -> RelationGraph"
        description: "Get node relationships for relation view (Mermaid graph data)"
      - name: "search_nodes"
        signature: "search_nodes(query: str, type_filter: Optional[str] = None) -> SearchResult"
        description: "Search nodes by keyword with type filtering"

  - id: dom_frontend
    name: "Frontend Infrastructure"
    description: "系统的'UI 工具包'，为所有项目提供前端开发规范和组件库能力。遵循 Spec-First 原则：组件 = MD文档(Truth) + HTML代码(Projection)。"
    exports:
      - name: "register_component"
        signature: "register_component(category: str, name: str, desc: str) -> Path"
        description: "Register a new component (creates MD design doc, updates index)"
      - name: "list_components"
        signature: "list_components() -> List[ComponentInfo]"
        description: "List all registered frontend components with status"
      - name: "validate_components"
        signature: "validate_components() -> ValidationResult"
        description: "Validate MD-HTML consistency for all components"
      - name: "get_component_index"
        signature: "get_component_index() -> ComponentIndex"
        description: "Get the component index for querying available components"
      - name: "get_usage_stats"
        signature: "get_usage_stats() -> Dict[str, int]"
        description: "Get component usage statistics across templates"

  - id: dom_quality
    name: "Quality Assurance"
    description: "系统的'免疫系统'，负责确保代码与 Spec 的一致性。"
    exports:
      - name: "check_consistency"
        signature: "check_consistency() -> ConsistencyReport"
        description: "Check PRD and YAML consistency"

  - id: dom_infra
    name: "Infrastructure"
    description: "系统的'血液循环'，提供日志、配置、错误处理等横切基础设施能力。"
    exports:
      - name: "get_logger"
        signature: "get_logger(name: str) -> Logger"
        description: "Get a named Logger instance"
      - name: "configure_logging"
        signature: "configure_logging(level: str = 'INFO', format: str = 'rich', log_file: Optional[Path] = None) -> None"
        description: "Configure global logging settings (called once at CLI entry point)"
      - name: "get_config"
        signature: "get_config(key: str, default: Any = None) -> Any"
        description: "Get a configuration value (Public API)"
      - name: "load_config"
        signature: "load_config(path: Path) -> Dict"
        description: "Load configuration from file (Public API)"
      - name: "load_env_file"
        signature: "load_env_file(path: Path = Path('.env')) -> None"
        description: "Load environment variables from .env file (Public API)"
      - name: "get_debug_mode"
        signature: "get_debug_mode(cli_flag: Optional[bool] = None) -> bool"
        description: "Get debug mode setting with priority: CLI > env > default (Public API)"
      - name: "handle_error"
        signature: "handle_error(error: Exception, context: Dict) -> None"
        description: "Unified error handling"
