# Product Root Definition (L-1 Level)
# 职责：定义产品愿景和领域概要，不包含 Feature 列表
# Feature 属于哪个 Domain 由 Feature YAML 中的 domain 字段声明

id: prod_devspec
name: "DevSpec"
version: "0.4.0"

# Product Vision - 用于需求分析 Step 2: 判断是否符合 Vision
description: |
  DevSpec 是一个严格的 **Specification Management System** (规范管理系统) 与 **CLI Orchestration Layer** (命令行编排层)。
  它面向 AI 辅助编程场景 (Claude CLI, Gemini CLI 等)，强制执行 **"Spec-First"** (文档优先) 工作流，并通过自动化的 **Consistency Checks** (一致性检查) 机制，确保代码实现对文档设计的绝对忠实 (Fidelity)，防止 AI 生成的代码随时间推移发生漂移 (Drift)。
  核心特性在于其 **Recursive Bootstrapping** (递归自举) 能力:它将自身的源码作为第一个管理对象，利用自身的上下文组装 (Context Assembly) 与代码分析 (Code Scanning) 能力，驱动 AI 完成工具自身的迭代与升级，实现开发环境的自我闭环
vision: |
  DevSpec 是专为 "Super Individuals" (超级个体) 设计的串行会话式智能结对编程环境。
  它不仅是开发业务软件的工具，更是一个自我进化的生命体 (Self-Evolving Life Form)。
  核心理念：Spec First (文档是唯一事实来源), Serial Flow (专注单任务), Recursive Evolution (工具由工具自身构建)。



# Domain 概要 (L0 Level) - 用于需求分析 Step 3: 分析涉及的 Domain
# 注意：不包含 features 列表，Domain → Feature 关系通过 Feature.domain 字段建立
domains:
  - id: dom_core
    name: "Core Engine"
    description: "系统的 Builder (构建者)，专注构建：解析代码、维护图谱、组装上下文。"
    exports:
      - name: "query_graph"
        signature: "query_graph(query: GraphQuery) -> List[Node]"
        description: "Query the SpecGraph knowledge graph"
      - name: "get_context"
        signature: "get_context(node_id: str, depth: int = 1) -> NodeGraph"
        description: "Get node context with related nodes"
      - name: "sync_graph"
        signature: "sync_graph() -> SyncResult"
        description: "Sync YAML files to database"

  - id: dom_cli
    name: "CLI Interface"
    description: "系统的 AI 接口，为 AI Agent 提供命令行工具，输出 Context 和建议。"
    exports:
      - name: "run_command"
        signature: "run_command(cmd: str, args: List[str]) -> int"
        description: "Execute a CLI command"

  - id: dom_specview
    name: "SpecGraph Viewer"
    description: "系统的人类窗口，提供 Web 界面展示知识库 (只读)。"
    exports:
      - name: "serve"
        signature: "serve(port: int = 8000) -> None"
        description: "Start the local web server for SpecGraph viewing"
      - name: "get_navigation_guide"
        signature: "get_navigation_guide() -> List[NavItem]"
        description: "Get navigation guide items for home page (Hierarchy, Design, Relations, Search)"
      - name: "get_node_relations"
        signature: "get_node_relations(node_id: str, depth: int = 2) -> RelationGraph"
        description: "Get node relationships for relation view (Mermaid graph data)"
      - name: "search_nodes"
        signature: "search_nodes(query: str, type_filter: Optional[str] = None) -> SearchResult"
        description: "Search nodes by keyword with type filtering"

  - id: dom_frontend
    name: "Frontend Infrastructure"
    description: "系统的'UI 工具包'，为所有项目提供前端开发规范和组件库能力。遵循 Spec-First 原则：组件 = MD文档(Truth) + HTML代码(Projection)。"
    exports:
      - name: "register_component"
        signature: "register_component(category: str, name: str, desc: str) -> Path"
        description: "Register a new component (creates MD design doc, updates index)"
      - name: "list_components"
        signature: "list_components() -> List[ComponentInfo]"
        description: "List all registered frontend components with status"
      - name: "validate_components"
        signature: "validate_components() -> ValidationResult"
        description: "Validate MD-HTML consistency for all components"
      - name: "get_component_index"
        signature: "get_component_index() -> ComponentIndex"
        description: "Get the component index for querying available components"
      - name: "get_usage_stats"
        signature: "get_usage_stats() -> Dict[str, int]"
        description: "Get component usage statistics across templates"

  - id: dom_quality
    name: "Quality Assurance"
    description: "系统的 Inspector (检查者)，专注验证：对比 Spec 与 Code，通过 Dashboard 报告问题。"
    exports:
      - name: "check_consistency"
        signature: "check_consistency() -> ConsistencyReport"
        description: "Check PRD and YAML consistency"

  - id: dom_infra
    name: "Infrastructure"
    description: "系统的 Support (支撑者)，提供日志、配置、Git Status Reader (只读感知器)。移除所有写操作能力。"
    exports:
      - name: "get_logger"
        signature: "get_logger(name: str) -> Logger"
        description: "Get a named Logger instance"
      - name: "configure_logging"
        signature: "configure_logging(level: str = 'INFO', format: str = 'rich', log_file: Optional[Path] = None) -> None"
        description: "Configure global logging settings (called once at CLI entry point)"
      - name: "get_config"
        signature: "get_config(key: str, default: Any = None) -> Any"
        description: "Get a configuration value (Public API)"
      - name: "load_config"
        signature: "load_config(path: Path) -> Dict"
        description: "Load configuration from file (Public API)"
      - name: "load_env_file"
        signature: "load_env_file(path: Path = Path('.env')) -> None"
        description: "Load environment variables from .env file (Public API)"
      - name: "get_debug_mode"
        signature: "get_debug_mode(cli_flag: Optional[bool] = None) -> bool"
        description: "Get debug mode setting with priority: CLI > env > default (Public API)"
      - name: "handle_error"
        signature: "handle_error(error: Exception, context: Dict) -> None"
        description: "Unified error handling"
